import type { RobloxAccount } from "@/lib/types/order";

/**
 * Centralized, deterministic assistant copy -- never generated by an LLM.
 * Keeping every workflow message here (rather than inline in components)
 * is what lets non-engineers change the wording later without touching
 * component code, and keeps fulfillment behavior independent of any future
 * AI layer (see project spec: AI may draft/suggest replies later, but
 * never decides state transitions).
 */
export const workflowMessages = {
  accountLinked: (account: RobloxAccount) =>
    `Perfect! 💜 Your Roblox account (${account.username}) has been linked successfully.`,
  readyCheck:
    "I'm preparing your delivery now. Please keep this page open — I'll guide you through each step.\n\nBefore we continue, please make sure:\n✓ You're logged into the Roblox account shown above\n✓ You can open the game\n✓ Trading is available on your account\n\nWhen you're ready, press the button below.",
  customerReadyAck:
    "You're all set! Your order has been added to the delivery queue.",
  waiting:
    "Please keep this page open. We'll update you here as soon as your delivery is ready.",
  agentAssigned: (agentName: string) =>
    `Great news — your delivery is ready. ${agentName} will be handling your order and will follow up here shortly.`,
  deliveryStarted:
    "Delivery is in progress. Please stay on this page and follow any instructions sent here.",
  deliveryComplete:
    "Your order has been successfully fulfilled. Thanks for choosing us! 💜",
} as const;

export const reassuranceMessages = [
  "Your order remains active while you wait.",
  "Your selected Roblox account is linked to this order.",
  "You'll receive the next instructions on this page.",
  "Having trouble? Send us a message below.",
] as const;
